name: Fetch and Deploy

on:
  schedule:
    - cron: '0 10,15,20 * * *'  # 07:00, 12:00, 17:00 BRT
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Fetch data
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: node scripts/fetchData.js

      - name: Commit changes if needed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/data/commits.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update commits data [skip ci]" && git push)

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist